# Generated by Django 4.2.7 on 2023-11-17 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuerpo', models.CharField(max_length=30)),
                ('destinatario', models.CharField(max_length=30)),
                ('emisor', models.CharField(max_length=30)),
                ('fecha_creacion', models.DateField()),
            ],
        ),
    ]
