# Generated by Django 4.2.7 on 2023-11-18 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensaje',
            name='fecha_creacion',
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='cuerpo',
            field=models.CharField(max_length=100),
        ),
    ]
