# Generated by Django 4.2.7 on 2023-11-11 00:50

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Criticas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('subtitulo', models.CharField(max_length=30)),
                ('critica', ckeditor.fields.RichTextField()),
                ('fecha_creacion', models.DateField()),
                ('imglibro', models.ImageField(blank=True, null=True, upload_to='imagen')),
            ],
        ),
    ]
