# Generated by Django 4.2.7 on 2023-11-11 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='criticas',
            old_name='subtitulo',
            new_name='autor',
        ),
    ]
