# Generated by Django 4.2.7 on 2023-11-12 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_subtitulo_criticas_autor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='criticas',
            old_name='imglibro',
            new_name='imgpeli',
        ),
    ]
