# Generated by Django 4.2.7 on 2023-11-12 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_imglibro_criticas_imgpeli'),
    ]

    operations = [
        migrations.RenameField(
            model_name='criticas',
            old_name='imgpeli',
            new_name='imagen_pelicula',
        ),
    ]
